### ISSUE TITLE
docker-compose.yml modifications

### ISSUE THREAD

**Issue by terry-sydaus** [raskitoma/pls_admin#6]
I had to modify the docker-compose.yml file to the following in order to get this app working, specifically to allow the adminpls docker instance to connect to the local postgresql database. If I did not make this change, then the adminpls container could not connect to the local postgresql database.

````yaml
services:
  adminpls:
    build: .
    image: adminpls:v1
    container_name: adminpls
    hostname: adminpls
    restart: always
    ports:
      - 8123:5000
    environment:
      - TZ=America/Guayaquil
      - APP_SETTINGS_MODULE=config.prod
    network_mode: "host"
    # networks setup depends on intercomm between other container stacks. Depends on declaration near the end of this file. This is optional
    # it's required if you setup a proxy reverse like nginx or connection to a DB inside the same machine
    # networks:
    #   master_network: # this is the network name

# setup other packages/services like db, proxy reverse, etc.
# setup network if required look at the "networks" section above
# networks:
#   master_network:
#     external: True
````
The change from the original file involves the addition of the following directive:

````yaml
    network_mode: "host"
````
